// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// image //
// ----- //

#define image_wrap_target 0
#define image_wrap 10
#define image_pio_version 0

static const uint16_t image_program_instructions[] = {
            //     .wrap_target
    0x20aa, //  0: wait   1 pin, 10
    0x202a, //  1: wait   0 pin, 10
    0x20a9, //  2: wait   1 pin, 9
    0x20ae, //  3: wait   1 pin, 14
    0x4008, //  4: in     pins, 8
    0x202e, //  5: wait   0 pin, 14
    0x20ae, //  6: wait   1 pin, 14
    0x4008, //  7: in     pins, 8
    0x202e, //  8: wait   0 pin, 14
    0x00c3, //  9: jmp    pin, 3
    0x0002, // 10: jmp    2
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program image_program = {
    .instructions = image_program_instructions,
    .length = 11,
    .origin = -1,
    .pio_version = image_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config image_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + image_wrap_target, offset + image_wrap);
    return c;
}

void image_program_init(PIO pio, uint sm, uint offset, uint pin_base) 
{
    // Pinos de dados (entrada) = GPIO12..GPIO26
    pio_sm_set_consecutive_pindirs(pio, sm, pin_base, 15, false);  //15 pinos a partir de base ficam entrada 
    pio_sm_config c = image_program_get_default_config(offset);
    sm_config_set_in_pins(&c, pin_base); // pinos usados no pio = (base..base+31)
    sm_config_set_jmp_pin(&c, 21);    // HREF usado no jmp pin
    sm_config_set_in_shift(&c, false, true, 16);  //config, shift_right, autopush, push threshold
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

